# Generated by Django 5.0.7 on 2024-08-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha_shop', '0002_alter_category_options_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcha_shop.key')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcha_shop.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcha_shop.value')),
            ],
        ),
    ]
