# Generated by Django 5.0.7 on 2024-08-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcha_shop', '0003_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name_plural': 'Attributes'},
        ),
    ]
