# Generated by Django 5.0.7 on 2024-08-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha_shop', '0005_product_is_liked_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='olcha_shop.product'),
        ),
    ]
