# Generated by Django 5.0.7 on 2024-08-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha_shop', '0007_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='olcha_shop.key'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='olcha_shop.product'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='olcha_shop.value'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='olcha_shop.product'),
        ),
    ]
